# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Craig Taylor
tagline:          Authentic | Collaborative | Technologist | Digital Transformation Addict
description:      "I have a passion for forging authentic relationships and using technology to help organisations reach their full potential. </br> I believe that open and honest conversation will break down silos."
url:              https://github.com/karloespiritu/blackdoc
baseurl:          /
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           Craig Taylor
  url:            https://www.linkedin.com/in/craig-taylor-4ab79715/

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.1

github:
  repo:             https://github.com/karloespiritu/blackdoc
